Compile with C++17
Some headers in mir include C++17 types such as std::optional so we need
to compile against C++17 also.

In file included from /usr/include/miral/miral/minimal_window_manager.h:21,
                 from /usr/include/qtmir/qtmir/windowmanagementpolicy.h:21,
                 from /home/pmos/build/src/lomiri-0.1.4/src/WindowManagementPolicy.h:20,
                 from /home/pmos/build/src/lomiri-0.1.4/src/LomiriApplication.cpp:38:
/usr/include/miral/miral/window_manager_tools.h:162:72: error: 'optional' in namespace 'std' does not name a template type
  162 |     auto window_to_select_application(const Application) const -> std::optional<Window>;
      |                                                                        ^~~~~~~~